port=0
interface=${LAN_IF}
bind-interfaces
dhcp-authoritative
dhcp-leasefile=/var/lib/misc/dnsmasq.leases

dhcp-range=192.168.1.100,192.168.1.200,255.255.255.0,12h
dhcp-option=option:router,192.168.1.1
dhcp-option=option:dns-server,192.168.1.1

dhcp-range=2001:db8:64::100,2001:db8:64::200,64,12h
dhcp-option=option6:dns-server,[2001:db8:64::1]